<dt>头条</dt>
                        <dd>
                            <h4>
                                <a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h4>
                            <p>
                               [field:description function='cn_substr(@me,158)'/]
                                <a href="[field:arcurl/]" target="_blank" title="详细">【详细】</a></p>
                        </dd>