<div class="fs_wrp">
          <ul class="fn" id="p_main">
            <li>
              <h4 id="p_fn_title" style="display:none;">[field:title/]</h4>
              <a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]" _src="[field:arcurl/]"  title="[field:title/]"  alt="[field:title/]" /></a></li>
          </ul>
        </div>
        <p class="fs_txt">[field:description function='cn_substr(@me,158)'/]……</p>
        <a href="[field:arcurl/]" title="+ 查看详情" target="_blank" class="fs_more">+ 查看详情</a>