<dt><span>
                        [field:pubdate function="MyDate('y-m-d',@me)"/]</span><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></dt>
                    <dd>
                        <p>
                            [field:description function='cn_substr(@me,58)'/]…
                        </p>
                        <a href="[field:arcurl/]" target="_blank" title="查看详情" class="n_more1">
                            + 查看详情</a>
                    </dd>