<li class=""><a href="[field:arcurl/]" class="h_img" title="">
                    <img src="[field:litpic/]" alt="" title="" /></a>
                    <h4><a href="[field:arcurl/]" title="" target="_blank">[field:title/]</a></h4>
                    <p>&nbsp;[field:description function='cn_substr(@me,58)'/]…
                    </p><a title="查看详情" href="[field:arcurl/]" target="_blank" class="h_xq">+ 查看详情</a> </li>