<dl>
                    <dt><b>
                        [field:pubdate function="MyDate('d',@me)"/]</b>[field:pubdate function="MyDate('y-m',@me)"/]</dt>
                    <dd>
                        <h4>
                            <a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h4>
                        <p>
                            [field:description function='cn_substr(@me,58)'/]…
                            <a title="详细" href="[field:arcurl/]" target="_blank">【详细】</a></p>
                    </dd>
                </dl>