<?php
$z[0]=Array("arcurl","",13,28);
$z[1]=Array("title","",49,63);
$z[2]=Array("litpic","",158,173);
$z[3]=Array("title","",180,194);
$z[4]=Array("title","",203,217);
$z[5]=Array("pubdate","",269,316);
$z[5][4]['function']="MyDate('y-m-d',@me)";
$z[6]=Array("arcurl","",332,347);
$z[7]=Array("title","",356,370);
$z[8]=Array("title","",388,402);
$z[9]=Array("description","",448,497);
$z[9][4]['function']="cn_substr(@me,58)";
$z[10]=Array("arcurl","",551,566);

?>