<li><a href="[field:arcurl/]" class="img" title="[field:title/]"
                                target="_blank">
                                <img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a>
                                <h4><span>[field:pubdate function="MyDate('y-m-d',@me)"/]</span><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h4>
                                <p>[field:description function='cn_substr(@me,58)'/] ……</p>
                                <a href="[field:arcurl/]" title="查看详情" target="_blank" class="xq">+ 查看详情</a> </li>