<dl class="fn">
                        <dt>
                            <a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]"  title="[field:title/]"  alt="[field:title/]" /></a></dt>
                        <dd>
                            <h4>
                                <a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h4>
                            <p>[field:description function='cn_substr(@me,158)'/]……
                                <a title="详细" href="[field:arcurl/]" target="_blank">【详细】</a></p>
                        </dd>
                    </dl>