<dl>
                            <dt><b>
                                [field:pubdate function="MyDate('d',@me)"/]</b>[field:pubdate function="MyDate('y-m',@me)"/]</dt>
                            <dd> <h4> <a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></h4>
                                <p> [field:description function='cn_substr(@me,158)'/]……<a href="[field:arcurl/]" target="_blank" title="详细">【详细】</a></p>
                            </dd>
                        </dl>