<?php
$z[0]=Array("global","(@me%2==0)?@me=\"fr\":@me=\"fl\";",11,97);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",119,134);
$z[2]=Array("title","",143,157);
$z[3]=Array("title","",175,189);
$z[4]=Array("dianhua","",222,238);
$z[5]=Array("chuanzhen","",267,285);
$z[6]=Array("youbian","",314,330);
$z[7]=Array("youxiang","",354,371);
$z[8]=Array("dizhi","",401,415);

?>