<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",226,361);
$z[0][4]['type']="son";
$z[0][4]['typeid']="3";
$z[0][4]['row']="7";
$z[1]=Array("arclist"," <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a> ",556,687);
$z[1][4]['row']="7";
$z[1][4]['titlelen']="30";
$z[1][4]['typeid']="7";
$z[2]=Array("global","",1433,1465);
$z[2][4]['name']="cfg_templets_skin";

?>