<?php
$z[0]=Array("global","",76,108);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]<em>[field:typenameen/]</em></a></li>\r\n    ",261,547);
$z[1][4]['type']="top";
$z[1][4]['row']="7";
$z[1][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~<em>~typenameen~</em></a></li>";

?>